---
- name: Create an EC2 instance
  hosts: localhost
  gather_facts: False
  tasks:
  - name: Launch instance
    ec2:
      key_name: tk_personal
      group: launch-wizard-1
      instance_type: t2.micro
      image: ami-017fecd1353bcc96e
      wait: true
      region: us-west-2
      register: ec2
  - name: Print all ec2 variables
    debug: var=ec2
  - name: Get the Ip address
    debug: var=ec2.instances[0].public_dns_name
  - name: add host to group 'ec2_hosts' with variable foo=42
    add_host:
      name: "{{ ec2.instances[0].public_dns_name }}"
      groups: ec2_hosts
      ansible_host: "{{ ec2.instances[0].public_dns_name }}"
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: "{{ lookup('env','SSH_KEYDIR') }}/tk_personal.pem"

  - name: Wait for a while
    pause: seconds=60

- name: run roles on remote box
  hosts: ec2_hosts
  become: true
  roles:
    - ubuntu_update
    - github
    - nginx
    - prometheus
    - node_exporter
    - grafana