---
- name: Create prometheus user
  user:
    name: prometheus
    state: present
    shell: /bin/false
    system: no
    createhome: no
  become_user: root

- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  with_items:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Unarchive a file that needs to be downloaded
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.39.1/prometheus-2.39.1.linux-amd64.tar.gz
    dest: /home/ubuntu
    remote_src: yes

- name: Copy file
  copy:
    src: /home/ubuntu/prometheus-2.39.1.linux-amd64/prometheus
    remote_src: yes
    dest: /usr/local/bin/
  become_user: root

- name: Copy file
  copy:
    src: /home/ubuntu/prometheus-2.39.1.linux-amd64/promtool
    remote_src: yes
    dest: /usr/local/bin/
  become_user: root

- name: Change file permission
  file:
    path: /usr/local/bin/prometheus
    owner: prometheus
    group: prometheus
    mode: '755'

- name: Change file permission
  file:
    path: /usr/local/bin/promtool
    owner: prometheus
    group: prometheus

- name: Copy file
  copy:
    src: /home/ubuntu/prometheus-2.39.1.linux-amd64/consoles
    dest: /etc/prometheus
    remote_src: yes

- name: Copy file
  copy:
    src: /home/ubuntu/prometheus-2.39.1.linux-amd64/console_libraries
    dest: /etc/prometheus
    remote_src: yes

- name: Change file permission
  file:
    path: /etc/prometheus/consoles
    owner: prometheus
    group: prometheus

- name: Change file permission
  file:
    path: /etc/prometheus/console_libraries
    owner: prometheus
    group: prometheus

- name: Delete unwanted files
  file:
    state: absent
    path: /home/ubuntu/prometheus-2.39.1.linux-amd64

- name: Delete unwanted files
  file:
    state: absent
    path: /home/ubuntu/prometheus-2.39.1.linux-amd64.tar.gz

- name: Copy file
  copy:
    src: /home/ubuntu/git/roles/prometheus/files/prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    remote_src: yes

- name: Change file permission
  file:
    path: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus

- name: Copy file
  copy:
    src: /home/ubuntu/git/roles/prometheus/files/prometheus.service
    dest: /etc/systemd/system/prometheus.service
    remote_src: yes

- name: Start prometheus
  systemd:
    state: started
    name: prometheus
    daemon_reload: yes
    enabled: yes